# http://docs.openstack.org/developer/heat/template_guide/hot_spec.html#heat-template-version
heat_template_version: 2014-10-16

# For more see http://hardysteven.blogspot.com.au/2014/09/using-heat-resourcegroup-resources.html

description: |
  A template to demonstrate resource groups. The resource group launches the basic instance template,
  passing the parameters entered through to it. It then returns the attributes and shows them as outputs.
  To run it, you need to launch it from the command line. Change directory to the directory this template
  is in, then use a command along the lines of:
  openstack stack create -f resource_group.yaml -P key_name=your_key resource_group_demo


parameters:

  key_name:
    type: string
    description: Name of an existing KeyPair to enable SSH access to the instances

  flavor:
    type: string
    description: The NeCTAR flavour the webserver is to run on
    default: t3.xsmall

  image:
    type: string
    description: ID of the image to use for the instance to be created
    default: NeCTAR Ubuntu 18.04 LTS (Bionic) amd64

  availability_zone:
    type: string
    description: Availability Zone


resources:
  resource_group:
    # http://docs.openstack.org/developer/heat/template_guide/openstack.html#OS::Heat::ResourceGroup
    type: "OS::Heat::ResourceGroup"
    properties:
      count: 2
      resource_def:
        type: "https://raw.githubusercontent.com/NeCTAR-RC/heat-templates/master/basic_server.yaml"
        properties:
          key_name: { get_param: key_name }
          image: { get_param: image }
          flavor: { get_param: flavor }
          availability_zone: { get_param: availability_zone }


outputs:
  attributes:
    description: A map of resource names to the specified attribute of each individual resource
    value: { get_attr: [ resource_group, attributes ] }

  refs:
    description: A list of resource IDs for the resources in the group
    value: { get_attr: [ resource_group, refs ] }

  first_resource_ref:
    description: The first resource reference
    value: {  get_attr: [ resource_group, resource.0 ] }

  instance_ip:
    description: The IP address of the deployed instance
    value: { get_attr: [ resource_group, resource.0.instance_ip ] }

  instance_networks:
    description: 'A dict of assigned network addresses of the form: {"public": [ip1, ip2...], "private": [ip3, ip4]}'
    value: { get_attr: [ resource_group, resource.0.instance_networks] }

  joined_networks:
    description: How to drill down (assuming that tasmania is the availibility zone in which the instance is running)
    value:  { list_join: [ ',', { get_attr: [ resource_group, resource.0.instance_networks, tas ] } ] }
