heat_template_version: 2021-04-16

description: |
  A template to demonstrate resource groups. The resource group launches the basic instance template,
  passing the parameters entered through to it. It then returns the attributes and shows them as outputs.


parameters:
  key_name:
    type: string
    description: Name of an existing Keypair to enable SSH access to the instances

  flavor:
    type: string
    description: The NeCTAR flavour the webserver is to run on
    default: t3.xsmall

  image:
    type: string
    description: ID of the image to use for the instance to be created
    default: NeCTAR Ubuntu 18.04 LTS (Bionic) amd64

  availability_zone:
    type: string
    description: Availability Zone


resources:
  resource_group:
    # http://docs.openstack.org/developer/heat/template_guide/openstack.html#OS::Heat::ResourceGroup
    type: "OS::Heat::ResourceGroup"
    properties:
      count: 2
      resource_def:
        type: "https://raw.githubusercontent.com/NeCTAR-RC/heat-templates/master/basic_server.yaml"
        properties:
          key_name: { get_param: key_name }
          image: { get_param: image }
          flavor: { get_param: flavor }
          availability_zone: { get_param: availability_zone }


outputs:
  attributes:
    description: A map of resource names to the specified attribute of each individual resource
    value: { get_attr: [ resource_group, attributes ] }

  refs:
    description: A list of resource IDs for the resources in the group
    value: { get_attr: [ resource_group, refs ] }
