heat_template_version: 2017-02-24
description: 'Sahara Node Group Template:

    master - worker'
parameters:
  master_name:
    type: string
    default: master
  worker_name:
    type: string
    default: worker
  plugin_name:
    type: string
    description: plugin name
    default: spark
  hadoop_version:
    type: string
    description: hadoop version
    default: 2.1.0
  master_node_processes:
    type: comma_delimited_list
    description: node processes for master instance
    default:
        - "namenode"
        - "master"
  worker_node_processes:
    type: comma_delimited_list
    description: node processes for worker instance
    default:
        - "datanode"
        - "slave"
  flavor:
    type: string
    description: instance flavor to be used
    default: m1.small
  auto_security_group:
    type: boolean
    description: auto-assign security group to this Node Group template
    default: True
  availability_zone:
    type: string
    description: AZ used for created server
    default: coreservices

resources:
  master_node_group:
    type: OS::Sahara::NodeGroupTemplate
    properties:
      name:
        str_replace:
          template: $nameprefix-$name
          params:
            $nameprefix: {get_param: "OS::stack_name"}
            $name: {get_param: master_name}
      flavor: {get_param: flavor}
      hadoop_version: {get_param: hadoop_version}
      node_processes: {get_param: master_node_processes}
      plugin_name: {get_param: plugin_name}
      auto_security_group: {get_param: auto_security_group}
      availability_zone: {get_param: availability_zone}
  worker_node_group:
    type: OS::Sahara::NodeGroupTemplate
    properties:
      name:
        str_replace:
          template: $nameprefix-$name
          params:
            $nameprefix: {get_param: "OS::stack_name"}
            $name: {get_param: worker_name}
      flavor: {get_param: flavor}
      hadoop_version: {get_param: hadoop_version}
      node_processes: {get_param: worker_node_processes}
      plugin_name: {get_param: plugin_name}
      auto_security_group: {get_param: auto_security_group}
      availability_zone: {get_param: availability_zone}
