parameters:
  master_name: master1
  worker_name: worker1
  plugin_name: spark
  hadoop_version: 2.1.0
  master_node_processes:
    - namenode
    - master
  worker_node_processes:
    - datanode
    - slave
  flavor: m1.tiny
  auto_security_group: True
  availability_zone: <AZ>
